# Generated by Django 5.1.7 on 2025-03-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.IntegerField()),
                ('period', models.TextField()),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_final_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_count', models.IntegerField()),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.statement')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('value_type', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('iban_partner', models.CharField(blank=True, max_length=34, null=True)),
                ('initial_sold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_sold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dailysummary')),
            ],
        ),
    ]
